OOH.WebApi/Models/Agency/AgencyVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OOH.WebApi.Models.Agency
{
    /// <summary>
    /// DTO web de entrada para agregar/editar una nueva agencia
    /// </summary>
    public class AgencyVm
    {
        public AgencyVm()
        {
            Id = 0;
        }

        /// <summary>
        /// Identificador de la agencia a a editar (por defecto 0 si es nueva)
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Nombre de la agencia
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Comision
        /// </summary>
        public float Rate { get; set; }
    }
}

OOH.WebApi/Controllers/AgenciesController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using OOH.Data.Helpers;
using OOH.Data.Interfaces;
using OOH.Data.Models;
using OOH.WebApi.Filters.Attributes;
using OOH.WebApi.Models.Agency;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OOH.WebApi.Controllers
{
    public class AgenciesController : Controller
    {
        [OhhFilter("ListAgencies", Data.ActionPermission.Read)]
        public async Task<IActionResult> Index()
        {
            return View();
        }

        #region private methods and functions

        #endregion
    }
}

OOH.WebApi/Views/Agencies/Index.cshtml
<div>
    <div class="card">

        <div class="card-header">
            <button class="btn btn-primary" id="btnAdd"> <i class="fa fa-pencil-square-o"></i>Agregar Agencia</button>
            <button class="btn btn-primary btn-outline-primary" onclick="refresh()"><i class="fa fa-refresh"></i>Actualizar</button>
        </div>
    </div>

    <div class="card">

        <div class="card-block">
            <table id="agencyTable" class="table table-hover">
                <thead>
                    <tr>
                        <th class="filter-action">Acciones</th>
                        <th class="filter">Código</th>
                        <th class="filter">Nombre de agencia</th>
                        <th class="filter">Comisión</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="modalAgency" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-lg h-100 d-flex flex-column justify-content-center my-0" role="document">
        <div class="modal-content">
            <form asp-controller="Agencies" asp-action="CreateUpdate" id="frmAgency" method="post">
                <div class="modal-header">
                    <h5 class="modal-title text-center w-100" id="modalTitle"></h5>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <input type="number" style="display:none" class="form-control number" name="Id" value="0" />
                        <div class="col-md-6">
                            <label>Nombre de agencia</label>
                            <input type="text" class="form-control" name="Name" />
                        </div>
                        <div class="col-md-6">
                            <label>Comisión</label>
                            @*<input type="number" class="form-control number" name="Rate" />*@
                            <div class="input-group input-group-default">
                                <span class="input-group-addon text-dark">%</span>
                                <input type="number" class="form-control number" name="Rate" />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                    <button type="button" class="btn btn-danger" id="btnClose">Cancelar</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section scripts{
    <script src="~/js/Agency/jquery.agency.js"></script>
}